# Generated by Django 5.1.15 on 2026-02-11 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(db_index=True, max_length=2)),
                ('price', models.FloatField(db_index=True)),
                ('lon', models.FloatField(blank=True, db_index=True, null=True)),
                ('lat', models.FloatField(blank=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['state', 'price'], name='routing_sta_state_b4c126_idx')],
            },
        ),
    ]
