# Generated by Django 5.1.15 on 2026-02-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='station',
            index=models.Index(fields=['lon', 'lat'], name='routing_sta_lon_c8b11f_idx'),
        ),
    ]
